### ISSUE TITLE
Adding a mechanism to pass the arguments to the callback?

### ISSUE THREAD

**Issue by roadcontrolsystems** [ricardocrudo/stimer#1]
Currently library passes stimer_t pointer to the callbacks.

Adding void* arg to the stimer_t struct and passing the arguments via stimer_start would be a good idea.

`struct stimer_t {`
    `  uint32_t time, counter;`
     `  int enabled, overflow;`
    `  stimer_mode_t mode;`
    `  void* arg;`
    `  void (*callback)(void *arg);`
`};`

and changing interface to the

`void stimer_start(stimer_t *timer, void* arg);`

Doing so, stimer can pass the necessary arguments to the callback function.

Of course, implementation will be changed according to this requirement.

**Comment by odurc** [comment]
That might be interesting, I wouldn't use `stimer_start` for that, though.
Can you give a real use case of this feature? (that can be useful for documentation)

Thanks for the suggestion.

**Comment by roadcontrolsystems** [comment]
We are using your library in a acoustic padestrian counttimer. During last 5 secons device sounds more frequently than before. 

Someone might need to pass her/his pointer when the timer fires. Users might have some issues when stimer is not aware of current context. 

For example, we want to play a sound when the timer fires. Type of the sound that should be played is based on the context. Also, we want to be able to start other timers that belong to the current context.

`typedef struct
{
	stimer_t* parent;
	stPhase_t phaseInfo;
}stTimerObject_t;`

/*Callback*/
`void overFiveSecondsFinishedEvent(stimer_t* timer, void* arg);`

/*Timer created in the context*/
`me->overFiveSecTimer = stimer_create(STIMER_ONE_SHOT, overFiveSecondsFinishedEvent);`

/*This is where we use stimer_start()*/
`
void acousticManager_phaseChangedEvent(void* me, stPhase_t* phaseInfo)
{
	static stTimerObject_t timerObj;
	stimer_stop(voidMe->overFiveSecTimer);
	stimer_stop(voidMe->fiveSecTimer);

	/*STOP anything playing*/
	jq6500_pause( voidMe->jq6500 );
		if( phaseInfo->previousPhaseDuration  > 5000 )
		{
			if(ePhase_green == phaseInfo->phaseType)
			{
					timerObj.parent    = me;
					timerObj.phaseInfo = *phaseInfo;

					stimer_set_time(voidMe->overFiveSecTimer, phaseInfo->previousPhaseDuration - 5000);
					stimer_start(voidMe->overFiveSecTimer, &timerObj);
`

/*Callback*/
`
void overFiveSecondsFinishedEvent(stimer_t* timer, void* arg)
{
	stTimerObject_t* timerObj = (stTimerObject_t*)arg;
	
	if( ePhase_green == timerObj->phaseInfo.phaseType )
	{
		jq6500_pause(((stAcousticManager_t*)(timerObj->parent))->jq6500);
		stimer_nop_wait(500);
		jq6500_select_track( ((stAcousticManager_t*)(timerObj->parent))->jq6500, timerObj->phaseInfo.sound);
	}
	
	stimer_start( ((stAcousticManager_t*)(timerObj->parent))->fiveSecTimer, arg );
}
`

**Comment by odurc** [comment]
I update the library and released the v1.2.0. I decided to create the function stimer_argument() to set a custom argument, this way the API does not break. Thanks for the suggestion.
