### ISSUE TITLE
I think the if-condition should be changed

### ISSUE THREAD

**Issue by opt12** [ricardocrudo/stimer#2]
Dear Ricardo,
while checking your code, I stumbled into this line:
https://github.com/ricardocrudo/stimer/blob/c9fb881f750aa0e7a2f20e7c7ef0d0adf356bf95/src/stimer.c#L185

I think, the condition should be changed to 
`if (timer->enabled == 1)`
Otherwise, a timer that was frred earlier using `stimer_destroy()` and eventually `stimer_give()` would not `continue`, but would be handled like an enabled timer. `-1 == TRUE`

Apart from that: Nice code. I think about "stealing" part of it in one of my embedded projects.

Regards,
opt12

**Comment by odurc** [comment]
Hello Felix, very nice catch!
I have fixed it, thank you.
